name: CI/CD Pipeline Basico

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  integracao_e_testes:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }} 
          POSTGRES_DB: express-crud
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Fazer o checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Node.js (Versão 20)
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Instalar as dependências (npm install)
      run: npm install

    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        DB_NAME: express-crud